### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by smaicloud** [mauricelambert/NetworkScanner#1]
```
from NetworkScanner import NetworkScanner
from asyncio import run

scanner = NetworkScanner(
	NetworkScanner.get_targets_from_network("192.168.178.0/23"),
	ping=True,
	arp=True,
	hostname=True,
	real_time=False,
	timeout=3)
run(scanner.scan())
print(scanner.hosts_up)
```
---
NetworkScanner  Copyright (C) 2021  Maurice Lambert
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

Traceback (most recent call last):
  File "ipcalc.py", line 12, in <module>
    run(scanner.scan())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/tkladmin/.local/lib/python3.8/site-packages/NetworkScanner/NetworkScanner.py", line 81, in scan
    await gather(*[self.test_ip(str(target)) for target in self.targets])
  File "/home/tkladmin/.local/lib/python3.8/site-packages/NetworkScanner/NetworkScanner.py", line 95, in test_ip
    process = await create_subprocess_shell(Constants.PING_COMMAND.value + ip, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.8/asyncio/subprocess.py", line 216, in create_subprocess_shell
    transport, protocol = await loop.subprocess_shell(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1597, in subprocess_shell
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1605, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files

---

/24 works

**Comment by smaicloud** [comment]
markdown code

**Comment by mauricelambert** [comment]
Thanks for opening this issue. The problem is the number of the PIPE created in the same time on your system. (*PIPE are "files" to read/write input/output of processes*). 

You can try to reduce the number of the PIPE:
 - Reduce the number of targets (by launching several scanners one after the other)
 - Reduce the number of subprocesses (choose between ARP and PING mode)

I will update this package and i will correct this bug.
