### ISSUE TITLE
Cannot execute, cannot import run from asyncio

### ISSUE THREAD

**Issue by danie-dejager** [mauricelambert/NetworkScanner#2]
I installed NetworkScanner using pip on Rocky 8.6 running python 3.6. I get the following error, even after I installed asyncio with pip

```
→ python3 NetworkScanner.pyz -h

NetworkScanner  Copyright (C) 2021, 2022  Maurice Lambert
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "NetworkScanner.pyz/__main__.py", line 290, in <module>
ImportError: cannot import name 'run'
```
```
→ python3 -m NetworkScanner -t 172.18.0.1-172.18.0.15

NetworkScanner  Copyright (C) 2021, 2022  Maurice Lambert
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/lynis/python3_env/lib/python3.6/site-packages/NetworkScanner.py", line 290, in <module>
    from asyncio import (
ImportError: cannot import name 'run'
```

**Comment by mauricelambert** [comment]
[See python documentation for asyncio.run, this function was created in 3.7, you can't use this tool in 3.6](https://docs.python.org/3/library/asyncio-runner.html#asyncio.run).

For security recommendations, [you should upgrade your python](https://devguide.python.org/versions/) (3.6 is End-Of-Life).
